// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertFileBufferFormat(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertFileBufferFormat'](arg1, arg2, arg3);
}

export function ConvertFileFormat(arg1, arg2) {
  return window['go']['main']['App']['ConvertFileFormat'](arg1, arg2);
}
