// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ProcessVideo(arg1:Array<number>,arg2:string):Promise<void>;

export function VideoBufferConverter(arg1:string,arg2:Array<number>,arg3:string):Promise<void>;
