// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ProcessVideo(arg1, arg2) {
  return window['go']['main']['App']['ProcessVideo'](arg1, arg2);
}

export function VideoBufferConverter(arg1, arg2, arg3) {
  return window['go']['main']['App']['VideoBufferConverter'](arg1, arg2, arg3);
}
